# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DooRiBon' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DooRiBon
  pod 'Alamofire', '~> 5.4'
  pod 'SnapKit', '~> 5.0.0'
  pod 'FSCalendar', :git => 'https://github.com/hyejinL/FSCalendar.git', :branch => 'dooribun'
   # Pods for FSCalendarPractice
end
